# Generated by Django 5.0.1 on 2024-02-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_car_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car',
            new_name='car_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
